name: PantryChef
options:
  bundleIdPrefix: com.souvik.pantrychef
  deploymentTarget:
    iOS: "16.0"
targets:
  PantryChef:
    type: application
    platform: iOS
    sources:
      - Sources
      - Resources
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_NAME: PantryChef
        PRODUCT_BUNDLE_IDENTIFIER: com.souvik.pantrychef
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: NO
